#pragma once

#define		PRIORITYBOOSTER					L"PriorityBooster"
#define		PRIORITYBOOSTER_SYS_FILE				PRIORITYBOOSTER L".sys"

// There are symbols for driver
#define		PRIORITYBOOSTER_DEVICENAME_DRV	L"\\Device\\" PRIORITYBOOSTER
#define		PRIORITYBOOSTER_LINKNAME_DRV 	L"\\??\\" PRIORITYBOOSTER

// There are symbols for command line app
#define		PRIORITYBOOSTER_LINKNAME_APP 	L"\\\\.\\" PRIORITYBOOSTER
#define		PRIORITYBOOSTER_SERVNAME_APP	PRIORITYBOOSTER

typedef struct _Thread_
{
	ULONG Id;
	int Priority;
} Thread, *PThread;

#define PRIORITY_BOOSTER_DEVICE 0x8000

#define FUNC_SET_PRIORITY  0x820

#define IOCTL_PRIORITY_BOOSTER_SET_PRIORITY CTL_CODE(PRIORITY_BOOSTER_DEVICE, FUNC_SET_PRIORITY, METHOD_NEITHER, FILE_ANY_ACCESS)